### ISSUE TITLE
dotnet new skoruba.duende.isadmin item with same key already added

### ISSUE THREAD

**Issue by tylerj-aft** [skoruba/Duende.IdentityServer.Admin#100]
### Describe the bug
When I run the dotnet new command, I get the errors listed below.

### To Reproduce

```
dotnet new skoruba.duende.isadmin --name Platform.Identity --title Platform.Identity --adminemail "admin@example.com" --adminpassword "Pa$$word123" --adminrole MyRole --adminclientid PlatformClientId --adminclientsecret PlatformClientSecret --dockersupport true
```

### Relevant parts of the log file

```
An item with the same key has already been added. Key: -p:a
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CliTemplateInfo template, Boolean validateDefaultLanguage)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IEnumerable`1 templatesToReparse, Boolean& languageOptionSpecified)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.GetTemplateCommand(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)
```

**Comment by skoruba** [comment]
Thank you for reporting this issue - it looks like something has been changed in dot net tools probably. 

I have to test it.

What version of .net tools do you use?

**Comment by tylerj-aft** [comment]
@skoruba  I've tried it using Windows 11 with Powershell (.NET 6 and 7 SDKs installed) as well as on Ubuntu with same SDKs installed via WSL and a VS Code terminal window. Same result.

**Comment by skoruba** [comment]
@tylerj-aft - thanks for info, I will test it.

**Comment by tylerj-aft** [comment]
@skoruba when I removed .NET 7 RC 2 the template installs without issue. It's just the presence of .NET 7 preview it seems.

**Comment by MarioBinder** [comment]
> @skoruba when I removed .NET 7 RC 2 the template installs without issue. It's just the presence of .NET 7 preview it seems.

@tylerj-aft Thanks!
Same here. After removing the "_7.0.100-rc.1.22431.12_" Folder from "_C:\Program Files\dotnet\sdk\_" it works fine.

**Comment by tylerj-aft** [comment]
@MarioBinder @skoruba thanks. For that and other tooling challenges (bleeding edge), I'm backing off .NET 7 for now.

**Comment by valdian** [comment]
> It works with SDK v7.0.101

I can confirm. 

With SDK 7.0.100, I got the same error as in the initial post.
Then I installed SDK 7.0.101, and it worked.
