### ISSUE TITLE
SSL Invalid: PartialChain (docker-compose)

### ISSUE THREAD

**Issue by cypherbuild** [skoruba/Duende.IdentityServer.Admin#106]
### Description
`AuthenticationException` when attempting to access the admin UI after initial build & run.
I can access `https://admin-api.skoruba.local/swagger` & `https://sts.skoruba.local` with no SSL errors.

I went through the steps with mkcert for some reason i don't think nginx config is handling the SSL passthrough correctly but I can't put my finger on it.

### Admin UI Reproduction
    1. Run project with docker-compose debug in vs
    2. Navigate to `https://admin.skoruba.local` 

### STS UI Reproduction
    1. Run project with docker-compose debug in vs
    2. Navigate to `https://admin.skoruba.local`
    3. Login with default admin credentails
    4. Click `IdentityServer Admin` button on NavBar

### Relevant parts of the log file

```
2022-11-23 17:10:46.335 -06:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'System.String'.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:44310)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by cypherbuild** [comment]
I may actually be able to debug this a little more.
I also noticed an issue with the dockery-compose debug where the output directory was actually set to .net5.0 instead of 6.0

**Comment by cypherbuild** [comment]
@skoruba could it be the URL mapping to the identity server within the docker network?

**Comment by apetrut** [comment]
Hi @cypherbuild ,

Can you confirm how you managed to run the https://sts.skoruba.local with no SSL errors?

I followed the manual from @skoruba  but this command line didn't work:
![image](https://user-images.githubusercontent.com/13006228/215326514-c2cb11a2-d654-4c38-8f6c-79439bf345da.png)

I have manually copied the certificate and .pem file and renamed them.
Now the volume in Docker looks like below and still doesn't work:

![docker_volume_ca_certificates](https://user-images.githubusercontent.com/13006228/215326538-1bbe9936-26b8-4f3c-b266-e7f1b791881a.jpg)

**Comment by albrookesplowman** [comment]
@apetrut / @cypherbuild - have either of you managed to find a solution to this problem as I am getting the same problem when running in docker

**Comment by apetrut** [comment]
@albrookesplowman I managed to run locally the admin project, by setting the correct certificate path like below:

![image](https://user-images.githubusercontent.com/13006228/218785946-0c1d8200-1ed4-4ebe-a4ba-125492a6a179.png)

However sometimes I get the same issues when navigating to the Admin page.

A similar issue has been opened [here]. (https://github.com/skoruba/Duende.IdentityServer.Admin/issues/124#issuecomment-1428544695)

**Comment by apetrut** [comment]
@albrookesplowman I have tried this approach and now it works on my machine.

![image](https://user-images.githubusercontent.com/13006228/218797610-d2597ccc-7c91-49ae-b51c-4c97aec902ba.png)

Can you confirm it's working on yours as well? Regards.

**Comment by apetrut** [comment]
@albrookesplowman regarding this exception:
`
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:44310)`

why is it showing localhost if the SSL certificates for skoruba.local are installed? It shouldn't use localhost anymore.

**Comment by albrookesplowman** [comment]
@apetrut - my problem was down to the location of the certificates.  I had updated the original dockerfile to build with the **runtime-deps:7.0-alpine** Microsoft image so that I can dramatically reduce the image size.  However, in doing this it stuffed up the certificates as apparently Alpine Linux expects the certificates to be in the **/etc/ssl/certs/** directory.  By simply changing the volume mapping in the docker compose file, it all burst back into life...  Don't know if that gives some pointers as to where your problem might be.  I also debugged it by using the terminal into the container to check that all the files were where I expected them to be...

**Comment by apetrut** [comment]
@albrookesplowman so you no longer get errors when you click `IdentityServer Admin` button on NavBar?

**Comment by albrookesplowman** [comment]
@apetrut - I get a different problem than before now but at least I can log in.,.. I get a 502 bad gateway error when I click on this button... but this appears to be coming from the nginx proxy.. I will let you know if I find anything

**Comment by albrookesplowman** [comment]
@apetrut - my bad gateway problem was down the config of the proxy.. 

I didn't have the vhost.d information configured correctly...

[https://stackoverflow.com/questions/48964429/net-core-behind-nginx-returns-502-bad-gateway-after-authentication-by-identitys](url)

**Comment by apetrut** [comment]
@albrookesplowman So now everything works properly using docker?

**Comment by albrookesplowman** [comment]
@apetrut - yep.. everything good now

**Comment by NickBuckland** [comment]
Hi All, I have just tried to follow up on your comments to see if I can resolve my issues, bit no success.
I'm back to 
https://sts.skoruba.local/ **works**
https://admin.skoruba.local/  **Error**
An unhandled exception occurred while processing the request.
AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain

I have tried add the certs into cacerts.crt folder
I have tried adding the parameters to nginx.conf

Any other suggestions?

@apetrut can you elaborate on how you updated the original dockerfile to build with the runtime-deps:7.0-alpine?

Thanks

**Comment by apetrut** [comment]
@NickBuckland 
I can load the admin.skoruba.local but can't load Aministrative page from time to time.

![image](https://user-images.githubusercontent.com/13006228/219083723-33bc230e-6562-4cc6-a502-ab8b02c2c862.png)

Have you run the following commands?

copy $env:LOCALAPPDATA\mkcert\rootCA-key.pem ./cacerts.pem
copy $env:LOCALAPPDATA\mkcert\rootCA.pem ./cacerts.crt

![image](https://user-images.githubusercontent.com/13006228/219090495-c58f4fb7-4534-46a3-ac3d-d5daa4a20b1b.png)

**Comment by albrookesplowman** [comment]
@NickBuckland - Please find attached a copy of the Dockerfile for the STS identity project for alpine and dotnet 7.  The other alterations I needed to make were to the project file to handle the globalization in the alpine images.

    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>true</PublishTrimmed>
    <InvariantGlobalization>false</InvariantGlobalization>

[Dockerfile.txt](https://github.com/skoruba/Duende.IdentityServer.Admin/files/10753649/Dockerfile.txt)

It brought the images down to about 150MB in size...

You can then make the same changes to the other dockerfiles...  Any problems then shout...

**Comment by NickBuckland** [comment]
Thanks @albrookesplowman so you are saying that I need to update each Dockerfile to pull the alpine image?
Unfortunately I'm not very experienced with Docker. There seem to be a lot of changes in the file you provided as opposed to the original file. Would i be able to just update the 'FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build' line or are more config changes required?
This is all a bit frustrating when all I want to do is spin-up IdentityServer using DockerCompose :/

**Comment by albrookesplowman** [comment]
@NickBuckland  - you will only need to update the dockerfiles if you want to use alpine .net 7.  if you just want to use the docker compose as is then it should all work out of the box.  It did for me.  I wanted to run .net 7 in smaller containers which is why I modified them.. Sorry if I have confused you further

**Comment by NickBuckland** [comment]
Thanks for your help @albrookesplowman !

The cert is mapped in the DockerCompose file 
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
      -
![image](https://user-images.githubusercontent.com/2473968/219359910-aa98f936-3b38-46a6-ae3a-92ce61435d1c.png)

**Comment by NickBuckland** [comment]
Hmm I have a new error now, I think it is progress :)
From the Admin site I see
SqlException: Invalid column name 'CoordinateLifetimeWithUserSession'.

This kind-a implies that it its at least trying to contact STS

**Comment by NadeemSadiq** [comment]
I tried cloning this project and trying but still seem to get this error. I went through the steps and have all the certificates and I can see the certificates in the containers but still no luck. Anything thing else I can do to test and make sure I haven't messed anything up? I copied the certificate so many times but I still can't seem to get it to work.

**Comment by NadeemSadiq** [comment]
I got it working. I am working in linux and when i made the mkcert i did ran it as admin but i tried again without admin (cleared everything before testing including the volumes) and retesting it (made sure to restart my browser when making/installing certificates). It works fine for me now.

**Comment by skoruba** [comment]
@NadeemSadiq - thanks for your feedback on this.

**Comment by apetrut** [comment]
@skoruba I am getting the same error now with v2.3.0 when I load the Admin UI page. The STS and Admin API are working fine.

![image](https://github.com/user-attachments/assets/ab9f059c-2069-40ac-9881-48719759d7f0)

**Comment by apetrut** [comment]
Turns out that removing the existing certificates and re-installing them from scratch (using the documentation found here) fixed the issue:
![image](https://github.com/user-attachments/assets/da6fe17c-0963-4ef4-9c37-920e6f52b1ce)
