### ISSUE TITLE
Could not find new Razor page

### ISSUE THREAD

**Issue by apetrut** [skoruba/Duende.IdentityServer.Admin#124]
HI @skoruba ,

I managed to run Admin UI locally using Docker-compose and I added one new UI called Tenants.cshtml.

These are the errors I've got:

![skoruba_local_missing_tenants_view](https://user-images.githubusercontent.com/13006228/215352198-11392ef7-ea88-400c-b71b-18640d9710a2.jpg)

I have checked the folder structure and the view is there:

![skoruba_local_vs_view_structure](https://user-images.githubusercontent.com/13006228/215352201-e18dc511-0a1f-4bf4-9446-515df648243c.jpg)

Important to mention is that using IIS (not Docker) the page loads just fine.
Is there another setting that needs to be enabled in order to pick up new views?

Thanks.

**Comment by skoruba** [comment]
Check csproj, if there is file correctly added.

**Comment by apetrut** [comment]
I found the lines below in .csproj file (it seems they are automatically added by VS):

![error_admin_ui_missing_view](https://user-images.githubusercontent.com/13006228/215455774-4955a3a3-5690-4d1a-ba89-8e226451f8b2.jpg)

If I remove the first 3 lines the UI stops working. Any ideas here?

**Comment by skoruba** [comment]
Sure, remove first item group, and keep rest of it.

**Comment by apetrut** [comment]
I tried that and got the error below:

![error_admin_ui_signin_oidc](https://user-images.githubusercontent.com/13006228/215549485-385ebcc5-1dab-47f2-8013-453f5c40aaac.jpg)

**Comment by skoruba** [comment]
that is different error, probable incorrect client secret.

**Comment by apetrut** [comment]
I haven't changed any client secret recently. Is there any way to get a more detailed error?

**Comment by skoruba** [comment]
yes, you can check logs in the sts.

**Comment by apetrut** [comment]
@skoruba the logs look like this and there is no other useful information. I am running your solution using docker-compose.

```
"/" Method Call 302 responded 1364.7796 in {6} ms
[2023-02-13T15:24:34.0329889+00:00][INFO][12][Microsoft.AspNetCore.Hosting.Diagnostics] Request finished HTTP/1.1 GET http://admin.skoruba.local/ - - - 302 0 - 1408.5986ms
[2023-02-13T15:25:16.6913638+00:00][INFO][23][Microsoft.AspNetCore.Hosting.Diagnostics] Request starting HTTP/1.1 POST http://admin.skoruba.local/signin-oidc application/x-www-form-urlencoded 627
[2023-02-13T15:25:16.8081150+00:00][EROR][23][Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler] Message contains error: '"invalid_request"', error_description: '"error_description is null"', error_uri: '"error_uri is null"', status code '400'.
[2023-02-13T15:25:46.4423613+00:00][EROR][23][Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler] Exception occurred while processing message.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_request', error_description: 'error_description is null', error_uri: 'error_uri is null'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
[2023-02-13T15:25:46.4472785+00:00][INFO][23][Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler] Error from RemoteAuthentication: "Message contains error: 'invalid_request', error_description: 'error_description is null', error_uri: 'error_uri is null'.".
```

**Comment by apetrut** [comment]
> that is different error, probable incorrect client secret.

@skoruba where can I change the client secret from and what value will work?

**Comment by apetrut** [comment]
@skoruba Do you have an update on this?

**Comment by apetrut** [comment]
I found the solution eventually in the STS Startup.cs class:

Add this line in the ConfigureServices method: `RegisterForwardedHeaders(services);

and also this method:

```
public virtual void RegisterForwardedHeaders(IServiceCollection services)
{
    services.Configure<ForwardedHeadersOptions>(options =>
    {
        options.ForwardedHeaders = ForwardedHeaders.All;
        options.KnownNetworks.Clear();
        options.KnownProxies.Clear();
    });
}
```

and then in the Configure method add this line:

`app.UseForwardedHeaders();`
