### ISSUE TITLE
Startup exception using docker image

### ISSUE THREAD

**Issue by abgithubuserab** [skoruba/Duende.IdentityServer.Admin#143]
Hi,
Hope someone can help.
I'm trying to run the admin UI using the images from dockerhub but an exception is occurring on startup in the admin UI project.
Seems to be when routes are being mapped.
Just wondering if I have missed something or anyone has had a similar issue.

Also not sure what the seed command should be for the admin dll as not sure of the compiled name in the image.
Should the seed command be:
command: dotnet MyProject.Admin.dll /seed
or
command: dotnet Skoruba.Duende.IdentityServer.Admin.dll /seed

Any help much appreciated.

### docker-compose.yml
[docker-compose.yml.txt](https://github.com/skoruba/Duende.IdentityServer.Admin/files/10784633/docker-compose.yml.txt)

### Image log
```
2023-02-20 12:50:46 [2023-02-20T12:50:46.1680900+00:00][FATL][18][Microsoft.AspNetCore.Hosting.Diagnostics] Application startup exception
2023-02-20 12:50:46 System.ArgumentNullException: Value cannot be null. (Parameter 'source')
2023-02-20 12:50:46    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2023-02-20 12:50:46    at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionDescriptorProvider..ctor(IEnumerable`1 pageRouteModelProviders, IOptions`1 mvcOptionsAccessor, IOptions`1 pagesOptionsAccessor)
2023-02-20 12:50:46    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2023-02-20 12:50:46    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
2023-02-20 12:50:46    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2023-02-20 12:50:46    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllerRoute(IEndpointRouteBuilder endpoints, String name, String pattern, Object defaults, Object constraints, Object dataTokens)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapAreaControllerRoute(IEndpointRouteBuilder endpoints, String name, String areaName, String pattern, Object defaults, Object constraints, Object dataTokens)
2023-02-20 12:50:46    at Skoruba.Duende.IdentityServer.Admin.UI.Helpers.ApplicationBuilder.AdminUIApplicationBuilderExtensions.MapIdentityServerAdminUI(IEndpointRouteBuilder endpoint, String patternPrefix) in /src/src/Skoruba.Duende.IdentityServer.Admin.UI/Helpers/ApplicationBuilder/AdminUIApplicationBuilderExtensions.cs:line 37
2023-02-20 12:50:46    at Skoruba.Duende.IdentityServer.Admin.Startup.<>c.<Configure>b__8_0(IEndpointRouteBuilder endpoint) in /src/src/Skoruba.Duende.IdentityServer.Admin/Startup.cs:line 63
2023-02-20 12:50:46    at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
2023-02-20 12:50:46    at Skoruba.Duende.IdentityServer.Admin.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory) in /src/src/Skoruba.Duende.IdentityServer.Admin/Startup.cs:line 61
2023-02-20 12:50:46    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2023-02-20 12:50:46    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
2023-02-20 12:50:46    at Skoruba.Duende.IdentityServer.Admin.UI.Helpers.StartupHelpers.StartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder) in /src/src/Skoruba.Duende.IdentityServer.Admin.UI/Helpers/StartupHelpers.cs:line 72
2023-02-20 12:50:46    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
2023-02-20 12:50:46    at Microsoft.AspNetCore.ForwardedHeadersStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
2023-02-20 12:50:46    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
2023-02-20 12:50:46    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

**Comment by ashliakhov** [comment]
@abgithubuserab 
Check if you you are passing some environment variable like:
```
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
```
Removing this one helped in my case
