### ISSUE TITLE
Exception: Correlation failed

### ISSUE THREAD

**Issue by albert0ly** [skoruba/Duende.IdentityServer.Admin#177]
An error after login.
It occurs very strange. On one computer works OK with "incognito". On another doesn't work with any mode and with any browser.

Other applications use Duende IdentityServer for authentication. The problem is only with Duende.IdentityServer.Admin.

```
An unhandled exception occurred while processing the request.

Exception: Correlation failed.

Unknown location

Exception: An error was encountered while handling the remote login.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

·      Stack 

·      Query 

·      Cookies 

·      Headers 

·      Routing

·        Exception: Correlation failed.


·         

Show raw exception details

System.Exception: Correlation failed.

·        Exception: An error was encountered while handling the remote login.

o   Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

o   Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

o   Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)

o   NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)

o   NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

o   NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

o   NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

o   NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

o   Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

·         

Show raw exception details

System.Exception: An error was encountered while handling the remote login.

---> System.Exception: Correlation failed.

   --- End of inner exception stack trace ---

   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
![IMG-20231008-WA0001](https://github.com/skoruba/Duende.IdentityServer.Admin/assets/139358895/10a06e4e-e3f0-4a4b-a96b-01aad9ca42b9)

**Comment by albert0ly** [comment]
Duende IdentityServer  and Admin on different machines, hosted on IIS.

**Comment by skoruba** [comment]
Sorry, this is a very old issue, so I’m going to close it now. My apologies for not responding earlier.
