### ISSUE TITLE
IdentityServer.Admin AuthenticationFailureException: Correlation failed

### ISSUE THREAD

**Issue by mtlive** [skoruba/Duende.IdentityServer.Admin#204]
### Describe the bug
Can not login to IdentityServer.Admin service.

### To Reproduce
Use http for all services.
.NET SDK 8.0.101
It doesn't happen if you use localhost instead of IP.
This problem **only happens in version 2. **

### Relevant parts of the log file

[12:52:19 ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Authentication.AuthenticationFailureException: An error was encountered while handling the remote login.
 ---> Microsoft.AspNetCore.Authentication.AuthenticationFailureException: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

**Comment by mtlive** [comment]
No update for this?

**Comment by mtlive** [comment]
@skoruba May you take a look at his?
Thank you

**Comment by 907080752** [comment]
me too

when i use ip ,that will exception correlation failed

**Comment by hello-ldf** [comment]
我碰到类似情况，并通过以下方式解决了。

首先，我的情况是 跳转到 IdentityServer.Admin 项目 /signin-oidc 的时候，报错了，日志如下。
![image](https://github.com/user-attachments/assets/540db08d-d731-480e-87b6-bf7b5e64b510)

其中，最关键的信息是
[16:34:19 WRN] '.AspNetCore.Correlation.Iq5tWpFpTUnvPy-gv_DB71Q7TjVCq0mszhBeM7JMGFM' cookie not found.

这个 cookie 找不到，然而，我断点时发现，这个 cookie 是存在的，只是被打上了 Secure=true，所以无法跨域修改。

于是，我大胆的在 IdentityServer.Admin 的 Startup::ConfigureService 底部加入了

services.Configure<CookiePolicyOptions>(options =>
{
    options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
    options.Secure = CookieSecurePolicy.SameAsRequest;
    options.OnAppendCookie = cookieContext =>
    {
        AuthenticationHelpers.CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
        **_cookieContext.CookieOptions.Secure = false;_**
    };
    options.OnDeleteCookie = cookieContext =>
    {
        AuthenticationHelpers.CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
        **_cookieContext.CookieOptions.Secure = false;_**
    };
});

关键在于把 Secure 设置为 false，这样，我发现该问题解决了。

可能第一次跳转会有问题，刷新页面多试几次就能进去了。

**Comment by ronelpanag** [comment]
Could somebody fix this?

**Comment by skoruba** [comment]
Sorry, this is a very old issue, so I’m going to close it now. My apologies for not responding earlier.
