### ISSUE TITLE
[mysql 5.7 && 8.0] Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by goodtogood** [skoruba/Duende.IdentityServer.Admin#46]
NET5 MySql 5.7 Win10 64bit

### Describe the bug

 Specified key was too long; max key length is 1000 bytesv

### To Reproduce

clone this repo , latest code
after modified appsettings.json then running Skoruba.Duende.IdentityServer.Admin
the log looks like below
I also tried using mysql8.0, the same result
I also read  issues about this problem #https://github.com/skoruba/IdentityServer4.Admin/issues/817 #https://github.com/skoruba/IdentityServer4.Admin/issues/256
but It did not work
thanks

### Relevant parts of the log file

```
2022-01-05 23:40:06.687 +08:00 [ERR] Failed executing DbCommand (7ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
CREATE INDEX `IX_PersistedGrants_SubjectId_ClientId_Type` ON `PersistedGrants` (`SubjectId`, `ClientId`, `Type`);
2022-01-05 23:40:06.875 +08:00 [FTL] Host terminated unexpectedly
MySqlConnector.MySqlException (0x80004005): Specified key was too long; max key length is 1000 bytes
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 888
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 271
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared.Helpers.DbMigrationHelpers.EnsureDatabasesMigratedAsync[TIdentityDbContext,TConfigurationDbContext,TPersistedGrantDbContext,TLogDbContext,TAuditLogDbContext,TDataProtectionDbContext](IServiceProvider services) in E:\id4\Duende.IdentityServer.Admin\src\Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared\Helpers\DbMigrationHelpers.cs:line 75
   at Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared.Helpers.DbMigrationHelpers.ApplyDbMigrationsWithDataSeedAsync[TIdentityServerDbContext,TIdentityDbContext,TPersistedGrantDbContext,TLogDbContext,TAuditLogDbContext,TDataProtectionDbContext,TUser,TRole](IHost host, Boolean applyDbMigrationWithDataSeedFromProgramArguments, SeedConfiguration seedConfiguration, DatabaseMigrationsConfiguration databaseMigrationsConfiguration) in E:\id4\Duende.IdentityServer.Admin\src\Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared\Helpers\DbMigrationHelpers.cs:line 52
   at Skoruba.Duende.IdentityServer.Admin.Program.ApplyDbMigrationsWithDataSeedAsync(String[] args, IConfiguration configuration, IHost host) in E:\id4\Duende.IdentityServer.Admin\src\Skoruba.Duende.IdentityServer.Admin\Program.cs:line 61
   at Skoruba.Duende.IdentityServer.Admin.Program.Main(String[] args) in E:\id4\Duende.IdentityServer.Admin\src\Skoruba.Duende.IdentityServer.Admin\Program.cs:line 38
```

**Comment by skoruba** [comment]
Hello @goodtogood - thanks for your feedback on MySQL, I am confused that this issue is still there. 🤔
I am testing new version with .NET 6 and the latest version of MySQL EF library and everything works - can you please check this PR: #44

Thanks!
