### ISSUE TITLE
Add Docker images for linux/arm64 platform

### ISSUE THREAD

**Issue by marcantoinecouture** [skoruba/Duende.IdentityServer.Admin#89]
**Is your feature request related to a problem? Please describe.**
The actual images are not working on `linux/arm64` platform, even with emulation.

The following error occurs:
```
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Skoruba.Duende.IdentityServer.STS.Identity.Program.GetConfiguration(String[] args) in /src/src/Skoruba.Duende.IdentityServer.STS.Identity/Program.cs:line 53
   at Skoruba.Duende.IdentityServer.STS.Identity.Program.Main(String[] args) in /src/src/Skoruba.Duende.IdentityServer.STS.Identity/Program.cs:line 15
qemu: uncaught target signal 6 (Aborted) - core dumped
```

Similar errors in Admin and Admin-Api

**Describe the solution you'd like**
Compile the Docker images for `linux/arm64` platform.

**Describe alternatives you've considered**
For the moment, I built the images locally and tagged like they were coming from Docker Hub. It actually works, but it would be great to have the images from Docker Hub. 

**Additional context**

**Comment by senzacionale** [comment]
I am running it on Ubuntu Linux without any problem.

**Comment by marcantoinecouture** [comment]
> I am running it on Ubuntu Linux without any problem.

Do you have an arm64 processor?
